### ISSUE TITLE
inlineKeyboard not working

### ISSUE THREAD

**Issue by Osamah** [botgram/botgram#12]
I am trying to implement an [inlineKeyboard ](https://core.telegram.org/bots/2-0-intro#new-inline-keyboards) in my Telegram bot, but keep getting following error:

> TelegramError: sendMessage failed: Bad Request: field "inline_keyboard" of the InlineKeyboardMarkup should be an Array of Arrays

I have tried with [the example you provided in the docs](https://github.com/botgram/botgram/blob/master/docs/callback.md#example), but keep getting the same error.

```
// People who are allowed to manipulate the volume
var ALLOWED_SENDERS = [ 8951984, 5091503, ... ];

bot.command("volumeknob", function (msg, reply, next) {
  reply.inlineKeyboard([
    { text: "↑  Turn up", data: JSON.stringify({ type: "volume", direction: true }) },
    { text: "↓  Turn down", data: JSON.stringify({ type: "volume", direction: false }) },
  ]);
  reply.text("Use the buttons below to modify the volume:");
});

bot.callback(function (query, next) {
  // Try to parse payload data as JSON. If we succeed, and `type` is set
  // to "volume" then the query is for us.
  var data;
  try {
    data = JSON.parse(query.data);
  } catch (e) {
    return next();
  }
  if (data.type !== "volume")
    return next();

  // Check sender is in whitelist
  if (ALLOWED_SENDERS.indexOf(query.from.id) === -1)
    return query.answer({ text: "Permission denied." });
  
  // Turn volume up or down
  if (data.direction) {
    system.volumeUp();
    query.answer();
  } else {
    system.volumeDown();
    query.answer();
  }
});
```

**Comment by jmendeth** [comment]
Hello,

just as the message says, the inline keyboard should be an Array of Arrays. Each array is a row of the keyboard with the corresponding buttons. Try i.e. this:

~~~ js
reply.inlineKeyboard(
  [
    [
      { text: "Turn up" },
      { text: "Turn down" }
    ],

    [
      { text: "Exit" },
      { text: "Reset" },
      { text: "Mute" }
    ]
  ]
);
~~~

Sorry about the example, there was a typo in it (it's pseudocode so I didn't check it extensively). The correct code should be an array with one row:

~~~ js
  reply.inlineKeyboard([ [
    { text: "↑  Turn up", data: JSON.stringify({ type: "volume", direction: true }) },
    { text: "↓  Turn down", data: JSON.stringify({ type: "volume", direction: false }) },
  ] ]);
~~~

instead of

~~~ js
  reply.inlineKeyboard([
    { text: "↑  Turn up", data: JSON.stringify({ type: "volume", direction: true }) },
    { text: "↓  Turn down", data: JSON.stringify({ type: "volume", direction: false }) },
  ]);
~~~

I'll correct that typo and add examples of inlineKeyboard

**Comment by asepmaulanaismail** [comment]
I was use this code: 
`reply.inlineKeyboard([ [
    { text: "↑  Turn up", data: JSON.stringify({ type: "volume", direction: true }) },
    { text: "↓  Turn down", data: JSON.stringify({ type: "volume", direction: false }) },
  ] ]);`

but there is error : TelegramError: sendMessage failed: Bad Request: can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard

**Comment by jmendeth** [comment]
Whooops, again my bad. It was `callback_data` instead of `data`. I have corrected the example code in the docs, it should work now.

I've also added a functional [`delete_echo.js`](https://github.com/jmendeth/node-botgram/blob/master/examples/delete_echo.js) example, you can look at it as well.

**Comment by asepmaulanaismail** [comment]
Thanks, it works

**Comment by jmendeth** [comment]
Closing issue, then.
By the way, I added the [`actions.js`](https://github.com/botgram/botgram/blob/master/examples/delete_echo.js) example which also uses inline keyboards.
