### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by carlostkd** [botgram/botgram#13]
hello, my installation was all ok without errors, but i can run the command /run for other commands i get a error "no command is running" i have tryied the commands cancel ende kill , and restart server but no lucky... any ideas??

thanks in advanced

**Comment by jmendeth** [comment]
that's weird, could you post a screenshot?

**Comment by jmendeth** [comment]
The shell bot has been moved to its own repository
https://github.com/botgram/shell-bot

The [blog post](https://jmendeth.com/blog/telegram-shell-bot) has also been updated since installation is much simpler now.
If you're still having problems with it, open an issue or comment on the blog.
