### ISSUE TITLE
TelegramError: can't use getUpdates method while webhook is active

### ISSUE THREAD

**Issue by asepmaulanaismail** [botgram/botgram#14]
I accidentally run node-botgram service and api.ai integrations with the same bot token, the service is crash. and when i try to run node-botgram service, i got this message:

`TelegramError: getUpdates failed: Conflict: can't use getUpdates method while webhook is active
`

how do i fixed that?
thanks

**Comment by asepmaulanaismail** [comment]
Sorry for this questions, i fixed that by deleted current webhook.

**Comment by jmendeth** [comment]
Yes, that's true. If you've used webhooks with your bot, you must disable them before trying botgram. I've added a [comment in the corresponding section](https://github.com/botgram/botgram/blob/master/docs/global.md#webhooks), but maybe we could go farther and automatically disable webhooks for the user?
