### ISSUE TITLE
Make the botgram plugin base

### ISSUE THREAD

**Issue by mehrunrasolian** [botgram/botgram#22]
Hey @jmendeth !
It will be awesome if you plan to implement a way to write some useful plugins for the but, like what [Telebot](https://github.com/mullwar/telebot/tree/master/plugins) is doing, but not so complex and buggy!

Awesome botgram!

**Comment by jmendeth** [comment]
Sorry for not getting in touch earlier! Botgram already supports middleware through the `bot.all()` function. I think middleware is a simpler way to add plugin-like functionality, it's what i.e. [Telegraf](https://github.com/telegraf/telegraf) and [Express](https://expressjs.com) do :)

As an example, here's an example middleware:

~~~ javascript
// Middleware to apologize to users when the bot is down
function apologizeIfQueued(msg, reply, next) {
    if (!msg.queued) return next()
    const { context, chat } = msg

    // If it's the first time we see this chat, decide if apology is needed
    if (context.apologize === undefined) {
        const downtime = Date.now() - msg.date.getTime()
        context.apologize = (downtime > 60 * 1000)
        if (context.apologize) {
            reply.text("🤖 Sorry! I was having problems, but I'm back online now.")
            console.error("Apologizing to %s %s (%s) for %ss downtime",
                chat.type, chat.id, chat.name, Math.ceil(downtime/1000))
        }
    }

    // If apology was not deemed necessary, process messages
    if (!context.apologize) return next()
}
module.exports = apologizeIfQueued
~~~

And here's how you'd use it in a project:

~~~ js
// ...
const apologizeIfQueued = require("apologize-if-queued")
const bot = botgram("TOKEN")
bot.all(apologizeIfQueued)
// ...
~~~

But unlike Telegraf, I don't have the time or resources to maintain various middlewares for Botgram, at least not ATM. :pensive:

**Comment by mehrunrasolian** [comment]
Great, I would like to work on it if I have tike for that.
Thank you!
