### ISSUE TITLE
NetworkError: getUpdates failed (after ~24 hours)

### ISSUE THREAD

**Issue by hrvstr** [botgram/botgram#23]
Hi, I am running a modified version of [shell-bot](https://github.com/botgram/shell-bot ). I just removed some of the commands and added my own. (I can post the code if needed)

After the bot is running smoothly for some hours (usually 1 day or so) it will stop responding to commands and spam the logs with these errors:

I am using OpenVPN and and a internet connection that restarts itself every 24 which might be the problem I think. Any advice what I would need to change to avoid restarting every 24h via cron?

Thanks!

````
  name: 'NetworkError',
  stack: 'NetworkError: getUpdates failed: Error: getaddrinfo EAI_AGAIN api.telegram.org:443\n    at new NetworkError (/home/dietpi/shell-bot/node_modules/botgram/lib/bot.js:20:20)\n    at ClientRequest.handleResponse (/home/dietpi/shell-bot/node_modules/botgram/lib/bot.js:133:24)\n    at emitOne (events.js:121:20)\n    at ClientRequest.emit (events.js:211:7)\n    at TLSSocket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:66:8)\n    at args.(anonymous function) (/usr/local/lib/nodejs/node-v8.15.0/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\nWhen calling method getUpdates: { offset: 273312714, timeout: 600 }\n    at Bot.callMethod (/home/dietpi/shell-bot/node_modules/botgram/lib/bot.js:102:18)\n    at Bot.consumeUpdates (/home/dietpi/shell-bot/node_modules/botgram/lib/bot.js:201:8)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)',
  message: 'getUpdates failed: Error: getaddrinfo EAI_AGAIN api.telegram.org:443',
  err: 
   { Error: getaddrinfo EAI_AGAIN api.telegram.org:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
     errno: 'EAI_AGAIN',
     code: 'EAI_AGAIN',
     syscall: 'getaddrinfo',
     hostname: 'api.telegram.org',
     host: 'api.telegram.org',
     port: 443 },
  req: 
   { Error: When calling method getUpdates: { offset: 273312714, timeout: 600 }
    at Bot.callMethod (/home/dietpi/shell-bot/node_modules/botgram/lib/bot.js:102:18)
    at Bot.consumeUpdates (/home/dietpi/shell-bot/node_modules/botgram/lib/bot.js:201:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     method: 'getUpdates',
     parameters: { offset: 273312714, timeout: 600 },
     message: 'When calling method getUpdates: { offset: 273312714, timeout: 600 }' } }
Error when updating: { NetworkError: getUpdates failed: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
    at new NetworkError (/home/dietpi/shell-bot/node_modules/botgram/lib/bot.js:20:20)
    at ClientRequest.handleResponse (/home/dietpi/shell-bot/node_modules/botgram/lib/bot.js:133:24)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at args.(anonymous function) (/usr/local/lib/nodejs/node-v8.15.0/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
When calling method getUpdates: { offset: 273312714, timeout: 600 }
    at Bot.callMethod (/home/dietpi/shell-bot/node_modules/botgram/lib/bot.js:102:18)
    at Bot.consumeUpdates (/home/dietpi/shell-bot/node_modules/botgram/lib/bot.js:201:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
````

I also checked if I have any webhooks attached to the bot but it does not seem to be the case:
`https://api.telegram.org/bot<token>/deleteWebhook`
`{"ok":true,"result":true,"description":"Webhook is already deleted"}`

**Comment by jmendeth** [comment]
The error is `getaddrinfo EAI_AGAIN api.telegram.org:443` which probably means Node.JS stops being able to reach the DNS server. Do your DNS settings change frequently?
Also, I understand the bot *does* work again just after restarting it?

**Comment by hrvstr** [comment]
My internet reconnects every 24 hours and so does OpenVPN, seems like this is confusing to Node.JS although it's always the same VPN server and DNS. The bot runs fine until I reconnect to the VPN, after that it won't respond anymore (in the chat to /help etc.) but still keeps "running" in the forever or pm2 process manager which is why it won't get restarted.

When I restart the process manually after a reconnect with `forever restartall` or `pm2 restart all` the bots starts responding again with no issues until I reconnect the VPN again.

So steps to reproduce would be:

1. Connect to VPN
2. Start shell-bot with `forever start server.js`
3. Run test command -> bot responds
4. Restart VPN with `systemctl restart openvpn.service`
5. Run test command -> no response from bot
6. Restart bot with `forever restartall`
7. Bot responds again.

I already tried adding a "up script" to my OpenVPN conf file but it does not seem to work. Other commands are being triggerd correctly (e.g. I am sending a message to the telegram bot on reconnect via the curl and the telegram API) but restarting the bot does not work for me.

**Comment by jmendeth** [comment]
Okay, everything clear now. Unfortunately I still haven't got a clue what makes DNS resolution fail. Could you execute this script? It performs a request every second. Try to see if it also starts having errors when OpenVPN reconnects:

~~~ js
const util = require("util")
const lookup = util.promisify(require("dns").lookup)
const delay = util.promisify(setTimeout)

; (async function () {
  while (true) {
    console.log("Looking up...")
    const result = await lookup("api.telegram.org").catch((e) => e)
    console.log(result)
    await delay(1000) 
  }
})()
~~~

**Comment by hrvstr** [comment]
Okay, so I ran your script alongside shell_bot in pm2.

````
┌──────────────┬────┬─────────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name     │ id │ version │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────────┼────┼─────────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ telegram_bot │ 0  │ 0.0.1   │ fork │ 5920 │ online │ 0       │ 3m     │ 0%  │ 30.2 MB   │ root │ disabled │
│ vpn_test     │ 1  │ 0.0.1   │ fork │ 6006 │ online │ 0       │ 0s     │ 0%  │ 19.3 MB   │ root │ disabled │
└──────────────┴────┴─────────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
````

After that I restarted my VPN service with `$ systemctl restart openvpn.service`

**Results:**
- telegram_bot does not respond anymore and has to be restarted manually.
- vpn_test keeps running and still outputs the following lines every second.

````
1|vpn_test  | Looking up...
1|vpn_test  | { address: '149.154.167.220', family: 4 }
````

---

In the meantime I managed to get the OpenVPN "up script" to work but I have to run pm2 and the telegram bot as root which I would like to avoid. Also long running process that happen during the reconnect would be aborted I think.

I added these lines to my OpenVPN config file:
````
script-security 2
up /etc/openvpn/up.sh
````
and the up script looks like this:
````
#!/usr/bin/env bash
sudo /usr/local/lib/nodejs/node-v8.15.0/bin/pm2 restart all
exit 0
````
