### ISSUE TITLE
Continuous bot shell reboot

### ISSUE THREAD

**Issue by fraraf85** [botgram/botgram#6]
hello I installed the shell bot, but every 10 min reboots by itself, why

**Comment by jmendeth** [comment]
I'd need to see the logs (if you're using forever, something like `forever logs 0` should show them)

**Comment by fraraf85** [comment]
Tomorrow the public will mistake coming out. starting it manually after a while it stops and leaves an error

**Comment by fraraf85** [comment]
here is what it says in the npm-debug.log file

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'owner',
1 verbose cli   'ls',
1 verbose cli   'botgram-shell' ]
2 info using npm@2.14.12
3 info using node@v4.3.2
4 silly mapToRegistry name botgram-shell
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/botgram-shell
8 verbose request uri https://registry.npmjs.org/botgram-shell
9 verbose request no auth needed
10 info attempt registry request try #1 at 18:40:49
11 verbose request id 30cfc389cbc2f946
12 http request GET https://registry.npmjs.org/botgram-shell
13 http 404 https://registry.npmjs.org/botgram-shell
14 verbose headers { 'content-type': 'application/json',
14 verbose headers   'cache-control': 'max-age=0',
14 verbose headers   'content-length': '2',
14 verbose headers   'accept-ranges': 'bytes',
14 verbose headers   date: 'Tue, 28 Feb 2017 17:40:51 GMT',
14 verbose headers   via: '1.1 varnish',
14 verbose headers   age: '0',
14 verbose headers   connection: 'keep-alive',
14 verbose headers   'x-served-by': 'cache-hhn1541-HHN',
14 verbose headers   'x-cache': 'MISS',
14 verbose headers   'x-cache-hits': '0',
14 verbose headers   'x-timer': 'S1488303651.522829,VS0,VE448',
14 verbose headers   vary: 'Accept-Encoding' }
15 silly get cb [ 404,
15 silly get   { 'content-type': 'application/json',
15 silly get     'cache-control': 'max-age=0',
15 silly get     'content-length': '2',
15 silly get     'accept-ranges': 'bytes',
15 silly get     date: 'Tue, 28 Feb 2017 17:40:51 GMT',
15 silly get     via: '1.1 varnish',
15 silly get     age: '0',
15 silly get     connection: 'keep-alive',
15 silly get     'x-served-by': 'cache-hhn1541-HHN',
15 silly get     'x-cache': 'MISS',
15 silly get     'x-cache-hits': '0',
15 silly get     'x-timer': 'S1488303651.522829,VS0,VE448',
15 silly get     vary: 'Accept-Encoding' } ]
16 error owner ls Couldn't get owner data botgram-shell
17 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/botgram-shell
17 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
17 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
17 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
17 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
17 verbose stack     at emitTwo (events.js:87:13)
17 verbose stack     at Request.emit (events.js:172:7)
17 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1082:10)
17 verbose stack     at emitOne (events.js:82:20)
17 verbose stack     at Request.emit (events.js:169:7)
17 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
18 verbose statusCode 404
19 verbose pkgid botgram-shell
20 verbose cwd /home/osmc/node-botgram/examples/shell
21 error Linux 4.4.27-7-osmc
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "owner" "ls" "botgram-shell"
23 error node v4.3.2
24 error npm  v2.14.12
25 error code E404
26 error 404 Registry returned 404 for GET on https://registry.npmjs.org/botgram-shell
26 error 404
26 error 404 'botgram-shell' is not in the npm registry.
26 error 404 You should bug the author to publish it (or use the name yourself!)
26 error 404
26 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]`

how can I fix?

**Comment by fraraf85** [comment]
debug.log

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'owner',
1 verbose cli   'ls',
1 verbose cli   'botgram-shell' ]
2 info using npm@4.3.0
3 info using node@v4.3.2
4 silly mapToRegistry name botgram-shell
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: 'botgram-shell',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: 'botgram-shell',
7 silly mapToRegistry   name: 'botgram-shell',
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   spec: 'latest',
7 silly mapToRegistry   type: 'tag' }
8 silly mapToRegistry uri https://registry.npmjs.org/botgram-shell
9 verbose request uri https://registry.npmjs.org/botgram-shell
10 verbose request no auth needed
11 info attempt registry request try #1 at 15:52:49
12 verbose request id eb4b3308e2220383
13 http request GET https://registry.npmjs.org/botgram-shell
14 http 404 https://registry.npmjs.org/botgram-shell
15 verbose headers { 'content-type': 'application/json',
15 verbose headers   'cache-control': 'max-age=0',
15 verbose headers   'content-length': '2',
15 verbose headers   'accept-ranges': 'bytes',
15 verbose headers   date: 'Wed, 01 Mar 2017 14:52:50 GMT',
15 verbose headers   via: '1.1 varnish',
15 verbose headers   age: '0',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'x-served-by': 'cache-hhn1547-HHN',
15 verbose headers   'x-cache': 'MISS',
15 verbose headers   'x-cache-hits': '0',
15 verbose headers   'x-timer': 'S1488379970.490895,VS0,VE449',
15 verbose headers   vary: 'Accept-Encoding' }
16 silly get cb [ 404,
16 silly get   { 'content-type': 'application/json',
16 silly get     'cache-control': 'max-age=0',
16 silly get     'content-length': '2',
16 silly get     'accept-ranges': 'bytes',
16 silly get     date: 'Wed, 01 Mar 2017 14:52:50 GMT',
16 silly get     via: '1.1 varnish',
16 silly get     age: '0',
16 silly get     connection: 'keep-alive',
16 silly get     'x-served-by': 'cache-hhn1547-HHN',
16 silly get     'x-cache': 'MISS',
16 silly get     'x-cache-hits': '0',
16 silly get     'x-timer': 'S1488379970.490895,VS0,VE449',
16 silly get     vary: 'Accept-Encoding' } ]
17 error owner ls Couldn't get owner data botgram-shell
18 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/botgram-shell
18 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
18 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
18 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
18 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
18 verbose stack     at emitTwo (events.js:87:13)
18 verbose stack     at Request.emit (events.js:172:7)
18 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1081:10)
18 verbose stack     at emitOne (events.js:77:13)
18 verbose stack     at Request.emit (events.js:169:7)
18 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1001:12)
19 verbose statusCode 404
20 verbose pkgid botgram-shell
21 verbose cwd /home/osmc/node-botgram/examples/shell
22 error Linux 4.4.27-7-osmc
23 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "owner" "ls" "botgram-shell"
24 error node v4.3.2
25 error npm  v4.3.0
26 error code E404
27 error 404 Registry returned 404 for GET on https://registry.npmjs.org/botgram-shell
28 error 404
29 error 404 'botgram-shell' is not in the npm registry.
30 error 404 You should bug the author to publish it (or use the name yourself!)
31 error 404 Note that you can also install from a
32 error 404 tarball, folder, http url, or git url.
33 verbose exit [ 1, true ]

**Comment by jmendeth** [comment]
The shell bot is an example included in botgram, so `npm install botgram`.

Please follow [the blog post](https://jmendeth.com/blog/telegram-shell-bot) carefully if you're having trouble.

**Comment by fraraf85** [comment]
I followed the guide on the forums to install it, and from that mistake

**Comment by jmendeth** [comment]
Umm are you sure? I'll try to reproduce tomorrow.
What command did you run?

**Comment by fraraf85** [comment]
to start it do this comman 
npm start <auth token> <your ID>
after a few minutes it stops and exits the above error

**Comment by jmendeth** [comment]
Oh, I see... I've updated the blog post. Try

    node server <auth token> <your ID>

instead of `npm start`.

**Comment by fraraf85** [comment]
nothing to do after a while it stops and I get this message from the terminal
> events.js:141
      throw er; // Unhandled 'error' event
      ^
NetworkError: Error: connect ETIMEDOUT 149.154.167.197:443
    at NetworkError.Error (native)
    at new NetworkError (/home/osmc/node-botgram/lib/bot.js:21:20)
    at ClientRequest.handleResponse (/home/osmc/node-botgram/lib/bot.js:129:24)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:437:9)

**Comment by jmendeth** [comment]
For some reason the bot cannot connect to Telegram servers, you should check your Internet connection / firewall... :face_with_head_bandage:

**Comment by fraraf85** [comment]
which can be the cause? the connection remains active. Use a raspberry

**Comment by fraraf85** [comment]
I made a continuous ping and I never packet losses, but the bot stops

**Comment by jmendeth** [comment]
Try doing a `wget https://api.telegram.org`

**Comment by fraraf85** [comment]
is a problem of telegram-api, which version is present in the code?

**Comment by jmendeth** [comment]
This module is called botgram, it's an alternative to node-telegram-bot-api.
It seriously appears to be a network problem... have you ever been able to run a bot in that Raspberry? Did that `wget https://api.telegram.org` work successfully?

**Comment by fraraf85** [comment]
is another bot works link https://github.com/karthikiyengar/teleshell

**Comment by jmendeth** [comment]
The shell bot has been moved to its own repository
https://github.com/botgram/shell-bot

The [blog post](https://jmendeth.com/blog/telegram-shell-bot) has also been updated since installation is much simpler now.
If you're still having problems with it, open an issue there or comment on the blog.
